version: '3'

services:
  spark:
    image: docker.io/bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    networks: 
      spark:
        ipv4_address: 172.19.0.100
    volumes:
      - spark-data:/tmp/spark-data        
  spark-worker-1:
    image: docker.io/bitnami/spark:latest
    container_name: spark-worker1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    #ports:
      #- '8081:8081'
      #- '7078:7077'
    networks: 
      spark:
        ipv4_address: 172.19.0.101
    volumes:
      - spark-data:/tmp/spark-data
  spark-worker-2:
    image: docker.io/bitnami/spark:latest
    container_name: spark-worker2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    #ports:
      #- '8082:8081'
      #- '7079:7077'      
    networks: 
      spark:
        ipv4_address: 172.19.0.102
    volumes:
      - spark-data:/tmp/spark-data
networks:
  spark:
    driver: bridge
    ipam:
      config: 
        - subnet: 172.19.0.0/16
volumes:
  spark-data:
    driver: local
    driver_opts: 
      type: "none"
      device: /Users/sjanakiraman/dev/spark/spark-data
      o: bind